version: "3"
services:
  selenium:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: .
    volumes:
      - .:/app
    ports:
      # for jupyter
      - 8888:8888
    env_file:
      - .env 
    tty: true
